### PR TITLE
Adding new attributes to redis server

### PR DESCRIPTION
**Pull request by deimosfr**
Hi,

I'd like to add those missing attributes:
- tcp-backlog
- slave-priority
- repl-disable-tcp-nodelay

Can you please merge ?

Thanks

### CODE REVIEW

**Comment by kamaradclimber** [comment]
At some point it would easier to let users specify parameters via an attributes hash instead of creating a new attribute for each parameter.

**Comment by brianbianco** [comment]
@kamaradclimber 100% what we would like to have this cookbook do. Hopefully sometime soon, we are always accepting pull requests as well :D

**Comment by deimosfr** [comment]
In waiting of this refactoring, can you please merge this pull request ?

**Comment by deimosfr** [comment]
Hi, any news ?
Thanks

**Comment by mhenrixon** [comment]
:+1:

**Comment by martinb3** [comment]
I've tested this as far back as redis 2.6, but I'm not sure when these settings were added. We'd probably just need to think about that, in relation to #199.

**Comment by eknudtson** [comment]
Could really use this PR, any news?

**Comment by zarry** [comment]
I wouldn't hold up the PR for that though @martinb3.  Supporting back to 2.6 is good enough for me as of now.   Again didn't have time for a in depth review but this looks pretty straight forward and I am good with a merge.

**Comment by brianbianco** [comment]
Has anybody tested this on redis 2.5?  If somebody could verify it works there I think this is ready to be merged.

**Comment by martinb3** [comment]
> At some point it would easier to let users specify parameters via an attributes hash instead of creating a new attribute for each parameter.

Opened a new issue for this -- #233. We can solve the longer term issue there.

**Comment by shortdudey123** [comment]
Looks like all 3 attributes were added and merged via https://github.com/brianbianco/redisio/pull/239
So this probably can be closed

**Comment by shortdudey123** [comment]
Superseded by https://github.com/brianbianco/redisio/pull/239

**Pull request closed without merging**
