### PR TITLE
Various systemd-related improvements

### LINKED ISSUE #271: Missing /usr/bin/redis-shutdown script
Hi,

I'm installing redis using cookbok version 2.4.2 on CentOS 7 using a wrapper cookbook (mainly to enforce version installed and default server settings).

I noticed the `systemd` script has its `ExecStop` command set to `/usr/bin/redis-shutdown`. However. when installing, this command does not exist. Is this file supposed to be present when installing by default?

This does not create apparent problem has `systemd` is smart enough to kill the process. However, for guaranteed persistence, the `redis` daemon must be  gracefully stopped. Also, even if the start command is templated with `%i`, the shutdown command seems not so I wonder what it was supposed to do.

ping @benLogN

### PR DESCRIPTION
**Pull request by chewi**
This fixes Debian/Ubuntu, fixes shutdowns with UNIX sockets, deals with multiple instances, and more.

It fixes #271 and #283. It supersedes #274.

### CODE REVIEW

**Comment by chewi** [comment]
Just added a further commit to create a systemd-tmpfiles entry after finding my server did not survive a reboot. At this point, I'm thinking the systemd cookbook would be a nice idea but I'll see what you think of all this first.

**Comment by brianbianco** [comment]
I usually like to avoid having dependencies on other cookbooks simply because it always seems to eventually cause some sort of headache.  However I currently am not steeped to deeply in the systemd world and haven't even looked at that cookbook.  It may be a good idea to use it.

**Comment by klyonrad** [comment]
What's the status of this one?

Are you planning to merge this Pull Request into the official repo soon? What blocks it?

cc @KieranHayes

**Comment by shortdudey123** [comment]
@chewi can you rebase this to solve the conflicts?

**Comment by chewi** [comment]
Done.

**Comment by shortdudey123** [comment]
Thanks!

**Pull request merged**
