### PR TITLE
Add repl-backlog-size, repl-backlog-ttl, and aof-load-truncated options

### PR DESCRIPTION
**Pull request by msaffitz**

### CODE REVIEW

**Comment by devsibwarra** [comment]
Looking to migrate from another redis cookbook to redisio.  The `repl-backlog-size` option is the only line from my previous config that I cannot migrate across.

This could be obsoleted by #233

**Comment by leevlad** [comment]
Can we get this merged at some point? Changes are straightforward and supported in the default config here:
http://download.redis.io/redis-stable/redis.conf

**Comment by brianbianco** [comment]
Looks like this merge has some conflicts.  Could @msaffitz rebase it off master?

**Comment by msaffitz** [comment]
@brianbianco I've rebased this

**Comment by leevlad** [comment]
@brianbianco possible to do a minor version bump?

**Comment by brianbianco** [comment]
Sure thing @leevlad

**Comment by leevlad** [comment]
Is there a process I'm missing for releasing a new minor version? My assumption was that @brianbianco would be the one controlling the release process. Do you need me to put together a PR for this? (thanks in advance for clarification)

**Comment by brianbianco** [comment]
Honestly the release process is typically handled through chefs supermarket.  The version number should be bumped in the metadata pretty liberally after a tagged version but sometimes that doesn't happen.  @zarry @martinb3 and myself have access to both the supermarket and github repo.

If you put together that PR that would be greatly appreciated.

**Comment by leevlad** [comment]
Thanks, here's a PR: https://github.com/brianbianco/redisio/pull/309

**Comment by leevlad** [comment]
cc @brianbianco

**Pull request merged**
