### PR TITLE
Only create the sentinel config files once

### PR DESCRIPTION
**Pull request by spuder**
Discussion in #231

Todo:

- [ ] Should redis and sentinel be restarted the first time the config file changes?
- [x] Is /var/tmp the best location for this file
- [x] Improve documentation & warn about deprecation.

### CODE REVIEW

**Comment by spuder** [comment]
Tested with kitchen, squashed commits, and removed the WIP from the title. Ready for review.

**Comment by spuder** [comment]
@martinb3  just curious if you have had time to look at this yet. From all my tests it is solid. Eager to discus if there are any concerns.

**Comment by spuder** [comment]
@brianbianco and @martinb3 Is there anything stopping this from being merged? I'd really like to get this into main.

**Comment by brianbianco** [comment]
What's stopping me is that I am on my honeymoon. Maybe @martinb3 or @zarry will have some time.

**Comment by spuder** [comment]
:bride_with_veil: :ring:  :clap:

**Comment by zarry** [comment]
@spuder took a quick look, essentially this just replaces the attribute concept with a file implementation?  Remove the file, the config will be updated.

**Comment by spuder** [comment]
Yes, it will create the config files once, and then leave them alone (as long as that 'protector' file exists). 

This prevents the situation where you have to set in your role / wrapper cookbook `node[:redisio][:sentinel][:manage_config] = true` then run chef, then change it back to `node[:redisio][:sentinel][:manage_config] = false` every time you want to deploy a new server.

**Comment by zarry** [comment]
Sweet, fixing my initial poor impl :+1:

**Comment by spuder** [comment]
Thanks. This has the bonus side affect of opening the door for letting chef safely restart the redis service if the configs change.

https://github.com/brianbianco/redisio/issues/220
https://github.com/brianbianco/redisio/issues/215

**Comment by spuder** [comment]
Got this change running in production. 

Before this change was accepted, chef would make the following changes to the sentinel config every time chef ran. 


```
       # redisio Cookbook additions
       daemonize yes
      -pidfile "/var/run/redis/sentinel_mycluster/sentinel_mycluster.pid"
      +pidfile /var/run/redis/sentinel_mycluster/sentinel_mycluster.pid
       loglevel notice
       syslog-enabled yes
      -syslog-ident "redis-mycluster"
      +syslog-ident redis-mycluster
       syslog-facility local0

      +
       # port <sentinel-port>
       # The port that this sentinel instance will run on
       port 26379
      @@ -48,14 +49,14 @@
       # Down).
       #
       # Default is 30 seconds.
      -sentinel failover-timeout mycluster_master 900000
      +sentinel down-after-milliseconds mycluster_master 30000
       # sentinel parallel-syncs <master-name> <numslaves>
       #
       # How many slaves we can reconfigure to point to the new slave simultaneously
       # during the failover. Use a low number if you use the slaves to serve query
       # to avoid that all the slaves will be unreachable at about the same
       # time while performing the synchronization with the master.
      -sentinel config-epoch mycluster_master 0
      +sentinel parallel-syncs mycluster_master 1
       # sentinel failover-timeout <master-name> <milliseconds>
       #
       # Specifies the failover timeout in milliseconds. When this time has elapsed
      @@ -70,7 +71,7 @@
       # "takeover".
       #
       # Default is 15 minutes.
      -sentinel leader-epoch mycluster_master 0
      +sentinel failover-timeout mycluster_master 900000
       # SCRIPTS EXECUTION
       #
       # sentinel notification-script and sentinel reconfig-script are used in order
      @@ -146,8 +147,4 @@
       # Example:
       #
       # sentinel client-reconfig-script mymaster /var/redis/reconfig.sh
      -# Generated by CONFIG REWRITE
      -dir "/"
      -sentinel known-slave mycluster_master 10.254.30.34 6379
      -sentinel current-epoch 0
```

Now nothing changes on subsequent chef runs. 

Add to berksfile until merged into master

```
cookbook 'redisio', github: "brianbianco/redisio", ref: "e81acf628ad71ad79ef34dab4239b5fc93b1f5d9" #https://github.com/brianbianco/redisio/pull/232
```

**Comment by sarkis** [comment]
@spuder thanks for the comment! I set my Berksfile to the commit for now and it looks good (sentinel configs not being updated on each chef run), however, I do see this:

```
  * redisio_sentinel[redis-sentinels] action run[2016-01-28T20:21:36+00:00] WARN: /var/chef/cache/cookbooks/redisio/providers/sentinel.rb:63:in `block (3 levels) in configure': property group is declared in both directory[/var/run/redis/sentinel_email-delivery] and #<#<Class:0x00000004232a40>:0x00000006ec6bb0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/redisio/providers/sentinel.rb:63:in `block (3 levels) in configure'
[2016-01-28T20:21:36+00:00] WARN: You are using a deprecated sentinel format. This will be removed in future versions.
[2016-01-28T20:21:36+00:00] WARN: /var/chef/cache/cookbooks/redisio/providers/sentinel.rb:138:in `block (3 levels) in configure': property group is declared in both template[/etc/redis/sentinel_email-delivery.conf] and #<#<Class:0x00000004232a40>:0x00000006ec6bb0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/redisio/providers/sentinel.rb:138:in `block (3 levels) in configure'
[2016-01-28T20:21:36+00:00] WARN: /var/chef/cache/cookbooks/redisio/providers/sentinel.rb:185:in `block (3 levels) in configure': property group is declared in both template[/etc/init/redis_sentinel_email-delivery.conf] and #<#<Class:0x00000004232a40>:0x00000006ec6bb0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/redisio/providers/sentinel.rb:185:in `block (3 levels) in configure'
```

Can you confirm if you see that as well?

**Comment by spuder** [comment]
@sarkis I'm not able to reproduce those warnings. Im using chef 12.6.0 on Ubuntu 14.04 with redis 3.0.7 

Berks
```ruby
source "https://supermarket.chef.io"

metadata

cookbook 'redisio', github: "brianbianco/redisio", ref: "e81acf628ad71ad79ef34dab4239b5fc93b1f5d9"
cookbook 'packagecloud', '~> 0.1.0'
cookbook 'apt'
```

kitchen
```yaml
---
driver:
  name: vagrant
  network:
  - ["forwarded_port", { guest: 4567, host: 4567 }]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[nd-redis::default]
      - recipe[redisio]
      - recipe[redisio::enable]
      - recipe[redisio::sentinel]
      - recipe[redisio::sentinel_enable]
    attributes:
      redisio:
        version: "3.0.7"
        safe_install: false
        default_settings:
          clusterenabled: "yes"
          clusternodetimeout: 5
```

**Pull request merged**
