### PR TITLE
Add SELinux support

### PR DESCRIPTION
**Pull request by chewi**

### CODE REVIEW

**Comment by shortdudey123** [comment]
You should also add in the conf dir since selinux assumes the conf files are `/etc/redis.*\.conf`

```
selinux_policy_fcontext "#{current['configdir']}(/.*)?" do
  secontext 'redis_conf_t'
end
```

**Comment by chewi** [comment]
Okay, added that.

**Comment by shortdudey123** [comment]
Think it would be relatively easy to add testing in test-kitchen, can you have a look at that?

**Comment by chewi** [comment]
Done! I think the Travis failure was unrelated.

**Comment by shortdudey123** [comment]
Re-triggered travis and it passes

**Pull request merged**
