### PR TITLE
Add encyrpted data bag support, fix systemd, add announce directives

### PR DESCRIPTION
**Pull request by shortdudey123**
- Add encyrpted data bag support
- Fix sysmtemd nofile limit (systemd does not honor `/etc/security/limits.d/` files)
- Add announce-ip and announce-port directives for sentinel

Verified as working in a test env

### CODE REVIEW

**Comment by JustinAiken** [comment]
This looks great :+1:

**Comment by brianbianco** [comment]
Thanks for this.  We will try to review this and get it in ASAP

**Comment by shortdudey123** [comment]
@brianbianco rebased on master to fix merge conflicts, let me know if you need anything from my sise

**Comment by shortdudey123** [comment]
@brianbianco any update on your end?  Been running this code in prod and it works great :)

**Comment by dwashko** [comment]
There is one issue I see with the implementation of the systemd nolimits.: The value is applied is the default settings value and ignores server overrides. This value also applies to all instances running on the server regardless of what the server max client override is set to. Not sure how much of an issue this could be but in the case where the server override is greater than the default value, this could be a problem. On the other hand, one could override the default value of max-clients to the value set in the server hash, but this seems counter intuitive to how the cookbook is working.

**Comment by shortdudey123** [comment]
@dwashko i was trying not to make a breaking change :p
Your way is a bit more correct, however it is a major breaking change

**Comment by dwashko** [comment]
good point.

**Comment by brianbianco** [comment]
@dwashko I have to agree with @shortdudey123.  While your implementation is probably more correct, I think not introducing a breaking change may be the way to go.  Thoughts on me merging #228 and closing #281 ?

**Comment by dwashko** [comment]
I am fine with it.

**Comment by shortdudey123** [comment]
@brianbianco one thought is to have this in your next minor rev and put https://github.com/brianbianco/redisio/pull/281 in the next major rev

**Comment by brianbianco** [comment]
@shortdudey123 A good idea certainly, I do hope the next major rev is basically a complete rewrite.  This cookbook was originally written long ago and there are just so much better ways to do things.

**Comment by shortdudey123** [comment]
haha fair enough

**Pull request merged**
