### PR TITLE
Chef 13 compatibility

### PR DESCRIPTION
**Pull request by shayangz**
Minor changes to fix Chef 13 compatibility issues.

### CODE REVIEW

**Comment by vitalis** [comment]
👍

**Comment by mateuszkwiatkowski** [comment]
What's needed to merge this PR? I'll be happy to help.

**Comment by nishiki** [comment]
I tested this patch with chef 13 and it works.
Can you merge this PR ?

Thanks

**Comment by brianbianco** [comment]
more importantly, will this change break compatibility with chef12?

**Comment by nishiki** [comment]
No, it's intended to works with chef 12, the point is the PR is stuck in silence.

**Comment by brianbianco** [comment]
I understand that it's stuck, the operative question was simply

Does this provide compatibility for newer versions without breaking it for older.  If the answer is yes, then it's fine to be merged.

**Comment by nishiki** [comment]
I see that the automated Travis check runs with Chef 12, isn't it enough to validate?

**Comment by brianbianco** [comment]
It's always nice if somebody tests it locally and confirms as well since the test suite is far from perfect.  I can merge now and we will just deal with the any issues that pop up though.

**Comment by rambler** [comment]
FWIW, this works for me (I'm using berkshelf to checkout the commit with the merge), in the context of sensu with Chef 13. I vote for a release!

**Comment by jarrettj** [comment]
👍  +1

**Comment by rmoriz** [comment]
@brianbianco can you please release the master branch to chef's supermarket?

**Comment by eren** [comment]
I tried this change with Chef version 13.5.3 and it's working perfectly fine. Please release `2.6.2` version of this cookbook and upload it to supermarket. @brianbianco 

I had to spend hours of debugging because I was originally using supermarket to install redisio cookbook and got the following error:

```
NameError: uninitialized constant Chef::Resource::RedisioConfigure
```

I checked out this repository master branch and start grepping strings. I couldn't find any reference because the code was already fixed and merged. However, the version string is still `2.6.1`. I later realized this github issue and saw that PR was merged. I installed this cookbook from git and it's now working. This is the line of my Berksfile:

```
cookbook 'redisio', '~> 2.6.1', git: "https://github.com/brianbianco/redisio.git", branch: "master"
``` 

I hope this explanation helps people who got similar error until the code is released in supermarket.

**Comment by thomasriley** [comment]
Could someone cut a release of this to supermarket? Seems a shame not to release when someone has put the time in to make this work on Chef 13.

Thanks!

**Comment by ssmlt** [comment]
Hello, are you able to bump cookbook version in metadata? 
Then Chef supermarket will take that release.
Because you merged the fix more than half year ago, but still not in supermarket :(

**Comment by majormoses** [comment]
@brianbianco if you need some help maintaining this let me know I am more than happy to help out as this is currently blocking us on a cookbook I maintain for sensu.

**Comment by brianbianco** [comment]
This sounds like a good plan. I can grant your github perms as well as chef supermarket. 

Feel free to shoot me a personal email if you want Brian.bianco@gmail.com

**Comment by majormoses** [comment]
Sounds good, either reply back to my email or this thread so I know I have access to cut and push a release.

**Comment by majormoses** [comment]
released:
- https://github.com/brianbianco/redisio/tree/v2.7.0
- https://supermarket.chef.io/cookbooks/redisio/versions/2.7.0

**Comment by scalp42** [comment]
@shayangz 💪

**Pull request merged**
