### PR TITLE
fix: STDERR: usermod: user redis is currently logged in

### PR DESCRIPTION
**Pull request by nathantsoi**

### CODE REVIEW

**Comment by martinb3** [comment]
Hello! It looks like this can't be merged against master. Could you rebase? Thanks!

**Comment by zarry** [comment]
@nathantsoi Ping for a rebase so we can get this merged.

**Comment by nathantsoi** [comment]
@zarry, done.

**Comment by martinb3** [comment]
Thanks @nathantsoi!

**Pull request merged**
