### PR TITLE
Fix sentinel instance required params sanity.

### PR DESCRIPTION
**Pull request by miguelcnf**
If I'm seeing this right the sanity would never fail.

### CODE REVIEW

**Comment by zarry** [comment]
Nice catch this looks good. Thank you for the contribution!

**Comment by martinb3** [comment]
Thank you @miguelcnf and @zarry; nice catch!

**Comment by miguelcnf** [comment]
@zarry @martinb3 no problem! Out of curiosity wondering why wasn't this merged?

**Comment by martinb3** [comment]
@zarry did this get merged in elsewhere? Let's re-open it just to be sure, as I don't see it merged in anywhere. :+1:

**Comment by zarry** [comment]
Honestly might just be a facepalm moment. I think I replied and used closed/comment before I merged, which I generally do the comment after the fact. 

Take 2.  Thanks again for the fix @miguelcnf

**Comment by miguelcnf** [comment]
Ahah no worries  :)

**Pull request merged**
