### PR TITLE
Add healthcheck for hot-standby cluster

### PR DESCRIPTION
**Pull request by autumnw**

### CODE REVIEW

**Comment by brianbianco** [comment]
Sorry this hasn't been reviewed yet.  I will try my best to get to this soon.

**Comment by martinb3** [comment]
I wonder if this should be using [the community xinetd cookbook](https://supermarket.chef.io/cookbooks/xinetd). Looks good to me otherwise, from a technical standpoint. I'm still not sure if this cookbook should be responsible for exposing checks like this at all (we should at least have multiple-instance sentinel support). I don't do enough monitoring of this sort to really say.

**Comment by brianbianco** [comment]
@martinb3 I hadn't even got that far in reviewing this.  That seems like a fairly correct assessment to me.    If we can get @zarry agreement the we should just close without merging.

**Comment by zarry** [comment]
I handle this exact xinetd setup in a wrapper cookbook around the redisio cookbook.  Specifically as it pertains to the sensu.  Which is how I can see you are using this as well since Sensu is still listed as the cookbook that recipe was grabbed from. 

I appreciate the effort and desire to get this shared but along with @martinb3 and @brianbianco I don't believe the reidiso cookbook is the right place for this.  I wouldn't be opposed to something in the readme pointing people to a gist or something should they need to do something like this.

**Comment by brianbianco** [comment]
@autumnw Thanks so much for the contribution.  We ultimately decided that while there is nothing wrong with this code, it isn't the responsibility of the redisio cookbook to handle it.

**Comment by autumnw** [comment]
Thanks guys. I got some better senses from here. I think I should create a new cookbook redis_cluster which will cover master-slave model and also active-active model.

**Pull request closed without merging**
