### PR TITLE
adding config settings for redis.conf.erb

### PR DESCRIPTION
**Pull request by drbayer**
* add rdbcompression to default settings & update template
* add dbfilename default setting & update template & provider
* add appendfilename default setting & update template & provider
* update template for slowlog-log-slower-than
* update template for slowlog-max-len
* add list-max-ziplist-entries to default settings & template for v2.6+
* add list-max-ziplist-value to default settings & template for v2.6+
* add tcp-backlog to default settings and template for v2.8+
* add slave-read-only to default settings and template for v2.6+
* add hll-sparse-max-bytes to default settings and template for v2.8+
* add rdbchecksum to default settings and template for v2.6+
* add repl-disable-tcp-nodelay to default settings and template for v2.6+
* add slave-priority to default settings and template

### CODE REVIEW

**Comment by martinb3** [comment]
Thank you for putting guards against specific versions for all of these :)

**Comment by drbayer** [comment]
I tried to prevent unexpected consequences as much as I could :-)

**Comment by scaryguy** [comment]
I'd like to use `tcpbacklog` attribute. Is this PR gonna be merged soon? While it's not merged, how can I make a patch? I need to set a tcpbacklog attribute.

**Comment by brianbianco** [comment]
PR looks good to me.  Sorry for the delay @scaryguy @drbayer

**Pull request merged**
