### PR TITLE
Added FreeBSD-10.3 support

### PR DESCRIPTION
**Pull request by tadukurow**
Hi,

I added FreeBSD-10.3 support and would be great if it could be part of the official redisio cookbook.
2 caveats: 
- installation from source is not supported because it would add a lot of extra dependencies for portsnap/portmaster and portsnap-downgrade
- setting ulimits is not supported because v0.1.2 of the ulimit cookbook is incompatible with FreeBSD (expects group 'root')

### CODE REVIEW

**Comment by brianbianco** [comment]
Wow thanks for the contribution, I'd really like to get this merged.  I'm a little backlogged at the moment.  Maybe somebody else will review it before me but I will try to make this a top priority.

**Comment by brianbianco** [comment]
Ok after reviewing this looks pretty good to merge to me.  I would have just one request for change or comment.  Would it make sense in the default attributes to assign package_install to true for freebsd since it does not support binary install?

**Comment by tadukurow** [comment]
Wow that's fast. 
Assigning package_install = true is probably more user friendly. i'll update the PR

**Comment by tadukurow** [comment]
I fixed some conflicts. 
Would it be possible to merge this PR?

**Comment by brianbianco** [comment]
Sure thing, I originally was just waiting for the default package install attribute.  Looks like you added that.  I will go ahead and merge this in.  Thanks for the hard work, glad to have freebsd support!

**Pull request merged**
