### PR TITLE
Do not prepend sentinel configured master name with sentinel_

### PR DESCRIPTION
**Pull request by matkam**
Resolves issue #161

### CODE REVIEW

**Comment by martinb3** [comment]
I think this PR fixes #108 and #161, but I find it confusing to take the name of a sentinel from the sentinels hash and call it 'master name' everywhere in the ruby code and rendered templates. We specifically allow the caller to supply a name for each sentinel in the hash. Why are we renaming the variable to 'master_name'? It's specifically not the name of a master, but the name for the sentinel (and the sentinel's init script, etc).

I also find it confusing that this PR is titled "do not prepend... with 'sentinel_'" and then it's got a few examples of prepending '_sentinel' in it:
```
- template "/etc/init.d/redis_#{sentinel_name}" do
+ template "/etc/init.d/redis_sentinel_#{master_name}" do
```
```
- template "#{current['configdir']}/#{sentinel_name}.conf" do
+ template "#{current['configdir']}/sentinel_#{master_name}.conf" do
```

Honestly, I would rather just fix the one template line in #161 that was confusing, than drop the concept of sentinels having a separate name. I also think it could get very, very confusing when we add support for watching multiple masters. A sentinel really shouldn't really have anything to do with the names of any of its masters, in my opinion, except specifically in the config file where you tell it what list of masters to watch.

**Comment by matkam** [comment]
Fair enough, you want to keep the concept of "sentinel name." How about I create a new PR that just adds support for "master_name?"

**Comment by martinb3** [comment]
What does `master_name` mean in the context of a sentinel watching more than one master?

**Comment by matkam** [comment]
Currently this cookbook only supports watching a single master. If you want to watch more than one, you'd have to modify the sentinel hash to support an array of ```master_name``` and corresponding ```master_ip```. The ```master_name``` is how the redis sentinel config refers to a group of redis sentinels watching a single master.

**Comment by martinb3** [comment]
We'd definitely like to add support for multiple masters (#73), so I didn't want to merge anything that goes backwards from that.

**Pull request closed without merging**
