### PR TITLE
Rubocop fixes from before

### PR DESCRIPTION
**Pull request by martinb3**
RE: https://github.com/brianbianco/redisio/pull/144, here are those rubocop fixes again against the latest master@HEAD. @brianbianco, @zarry -- let me know what you think. We still need to go back and fix chef 12 compatibility, but that was failing before I started.

### CODE REVIEW

**Comment by zarry** [comment]
I did a rather quick review of these changes.  It all looks fine to me.  I would support the merge of this, wouldn't mind @brianbianco thoughts.

As long as the test suite is passing I feel confident enough in these stylistic/formatting changes.

**Comment by brianbianco** [comment]
Looks good to me.  I'm almost embarassed to look at configure.rb.  I think the changes make that abomination a bit more readable.  

Has anybody run the test suite against this?  If so, I think this should be merged.

**Comment by martinb3** [comment]
I have been running the tests on it while I was working on it. I believe they're all currently passing.

**Comment by martinb3** [comment]
This will likely need to be redone again.

**Pull request closed without merging**
