### PR TITLE
enable diskless replication configuration

### PR DESCRIPTION
**Pull request by popsikle**

### CODE REVIEW

**Comment by popsikle** [comment]
Sigh.

**Comment by arpad9** [comment]
Well, thanks anyway @popsikle  Made it easy for me to apply the changes to my fork.

**Comment by popsikle** [comment]
@arpad9 no prob ;p

**Comment by shortdudey123** [comment]
`slave-read-only` was added in https://github.com/brianbianco/redisio/pull/253
So this can be rebased to only adding `repl-diskless-*` and should take into account >2.x also

**Comment by shortdudey123** [comment]
Carried by https://github.com/brianbianco/redisio/pull/340

**Pull request closed without merging**
