### PR TITLE
Cleanup warnings

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by shortdudey123** [comment]
@brianbianco any thoughts?

**Comment by shortdudey123** [comment]
@brianbianco can you review this when you have a sec?  This will help keep the cookbook from breaking in April w/ chef 13

**Comment by brianbianco** [comment]
Is there a reason the switch from .set to default / override is bundled up in the same PR as changing the managed home for chef 13?  It feels like the switching off .set could potentially break things for some people.  Although I don't think anybody would be relying on the persistence of the data, somebody could be.

**Comment by shortdudey123** [comment]
Outside of the spec testing, the only `.set` change is in `recipes/configure.rb`.  I will use `.normal` instead since its the same as `.set`, but generally speaking attribute persistence is not recommended unless really needed.  So eventually that will need to be changed, but it is a breaking change.

**Comment by shortdudey123** [comment]
@brianbianco updated :)

**Comment by brianbianco** [comment]
I agree that attribute persistence should be eliminated, but like you said the breaking change is what i was lookinn to avoid.  Breaking changes should usually be their own PR instead of tucked inside others.

**Comment by shortdudey123** [comment]
True, will remember that for the future
thanks!

**Pull request merged**
